## ECG Processing Pipeline: Steps

### 1. Starting point
* Raw ECG data is loaded from 'data/ECGu.txt' as a NumPy array.

### 2. Analysis Steps
1. **Inspection & Plotting**: Visualize raw signal channels over time to check data quality.
2. **Preprocessing / Filtering**: Remove noise and baseline wander using bandpass filtering.
3. **QRS / R-peak Detection**: Detect R-peaks to identify individual heartbeats.
4. **Heart Rate Calculation**: Compute RR intervals and heart rate in beats per minute (BPM).

### 3. Target Output
* Accurate heart rate metrics (instantaneous BPM, average BPM) and clear visual plots of filtered signals with detected peaks.

In [2]:
# CELLULE 1 : importations
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# CELLULE 2 : charger les donnees dans un tableau NumPy
ecg_raw = np.loadtxt("data/ECGu.txt")

In [4]:
# CELLULE 3 : examinez les donnees (verifiez que les donnees sont correctement chargees)
print(ecg_raw)
print(ecg_raw.shape)

[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 ...
 [  -4.  -83.   21.]
 [  -9.  -88.   31.]
 [ -16.  -96.   33.]]
(6500, 3)
