# ECG Data Processing Pipeline

## 1. Loading and Inspecting ECG Data
The objective of this step is to load the raw ECG signal from the text file located in the `data/` folder and verify its contents.

In [1]:
import numpy as np

# Load the data from the text file
ecg_data = np.loadtxt(r"C:\Users\ZSAUGE.NDSJ\OneDrive - Université de Franche-Comté (univ-fcomte.fr)\Documents\masterIEAP\Python-R-git\Series01\Series01-python\data\ECGu.txt")

# Display the first 10 data points to verify proper loading
print("First 10 data points from the ECG data:")
print(ecg_data[:10])

First 10 data points from the ECG data:
[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 [-275. -121. -112.]
 [-273. -120. -105.]
 [-274. -124. -101.]
 [-274. -126.  -86.]
 [-273. -126.  -73.]
 [-270. -125.  -70.]
 [-274. -120.  -80.]]


## ECG Processing Pipeline: Steps

### 1. Starting point
* Raw ECG data is loaded from 'data/ECGu.txt' as a NumPy array.

### 2. Analysis Steps
1. **Inspection & Plotting**: Visualize raw signal channels over time to check data quality.
2. **Preprocessing / Filtering**: Remove noise and baseline wander using bandpass filtering.
3. **QRS / R-peak Detection**: Detect R-peaks to identify individual heartbeats.
4. **Heart Rate Calculation**: Compute RR intervals and heart rate in beats per minute (BPM).

### 3. Target Output
* Accurate heart rate metrics (instantaneous BPM, average BPM) and clear visual plots of filtered signals with detected peaks.